# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='plan',
            new_name='description',
        ),
    ]
